global:
  resolve_timeout: 5m
inhibit_rules:
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = critical
  target_matchers:
  - severity =~ warning|info
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = warning
  target_matchers:
  - severity = info
- equal:
  - namespace
  source_matchers:
  - alertname = InfoInhibitor
  target_matchers:
  - severity = info
- target_matchers:
  - alertname = InfoInhibitor
receivers:
- name: grafana-oncall
  webhook_configs:
  - send_resolved: true
    url: https://incident-prod-eu-west-6.grafana.net/oncall/integrations/v1/alertmanager/3RSo7ZviVQjT0yqZaXEST5aUp/
- name: "null"
route:
  group_by:
  - alertname
  - namespace
  group_interval: 1m
  group_wait: 30s
  receiver: grafana-oncall
  repeat_interval: 1m
  routes:
  - matchers:
    - alertname = "Watchdog"
    receiver: "null"
  - matchers:
    - alertname = "InfoInhibitor"
    receiver: "null"
templates:
- /etc/alertmanager/config/*.tmpl